apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service-rest-api
  labels:
    app: feed-service-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-service-rest-api
  template:
    metadata:
      labels:
        app: feed-service-rest-api
    spec:
      containers:
      - name: feed-service-rest-api
        image: sachinsharma1001/feed-service-rest-api:latest
        imagePullPolicy: Always 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15  
            periodSeconds: 20      
        env:
          - name: POSTGRESS_USERNAME
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRESS_USERNAME 
          - name: POSTGRESS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRESS_PASSWORD
          - name: POSTGRESS_DATABASE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRESS_DATABASE 
          - name: POSTGRESS_HOST
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRESS_HOST
          - name: POSTGRESS_DIALECT
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRESS_DIALECT
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_REGION
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_PROFILE      
        ports:
        - containerPort: 8080